import { Router } from 'express';
import authRoutes from './auth.js';
import farmerRoutes from './farmer.js';
import marketplaceRoutes from './marketplace.js';
import orderRoutes from './orders.js';
import bulkBuyerRoutes from './bulkBuyer.js';
import fpoRoutes from './fpo.js';
import logisticsRoutes from './logistics.js';
import adminRoutes from './admin.js';
import notificationRoutes from './notifications.js';
import reviewRoutes from './reviews.js';
import complaintRoutes from './complaints.js';
import aiRoutes from './ai.js';
const router = Router();
router.use('/auth', authRoutes);
router.use('/farmer', farmerRoutes);
router.use('/marketplace', marketplaceRoutes);
router.use('/orders', orderRoutes);
router.use('/bulk-buyer', bulkBuyerRoutes);
router.use('/fpo', fpoRoutes);
router.use('/logistics', logisticsRoutes);
router.use('/admin', adminRoutes);
router.use('/notifications', notificationRoutes);
router.use('/reviews', reviewRoutes);
router.use('/complaints', complaintRoutes);
router.use('/ai', aiRoutes);
export default router;
